
FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
#ENV TZ=Israel
ENV MSSQL_PID=Express
ENV SA_PASSWORD=PlanarSqlPassword12345@

COPY ./data /

ENTRYPOINT [ "/bin/bash", "entrypoint.sh" ]
CMD [ "/opt/mssql/bin/sqlservr" ]