BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Roles ADD CONSTRAINT
	FK_Roles_Roles FOREIGN KEY
	(
	Id
	) REFERENCES dbo.Roles
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Roles SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.UsersToGroups
	DROP CONSTRAINT FK_UsersToGroups_Users
GO
ALTER TABLE dbo.Users
	DROP CONSTRAINT FK_Users_Users
GO
ALTER TABLE dbo.Users ADD CONSTRAINT
	FK_Users_Roles FOREIGN KEY
	(
	RoleId
	) REFERENCES dbo.Roles
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Users SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.UsersToGroups ADD CONSTRAINT
	FK_UsersToGroups_Users FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.UsersToGroups SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
