defaults:                                       # default values for all keys. each key can override these values
  retry count: 3                                # the number of retry attemp in case of failure
  retry interval: 00:00:03                      # the interval between retry attemps
  maximum fails in row: 5                       # the maximum number of fails in row before the job is considered as failed
  database: 0                                   # defualt redis database number to be used

# redis:                                        # the redis server parameters to be use. usualy this section defined in specific environment job settings
#   endpoints: 
#     - redis-server-1:6379
#     - redis-server-2:6379
#   ssl: false
#   user: null
#   password: null

health check: 
  ping: true                                    # the job will fail if the ping is not ok
  latency: 1000                                 # the maximum ping latency in ms
  connected clients: 9000                       # the maximum number of connected clients (the default redis server maximum connected clients is 10,000)
  used memory: 10mb                             # the maximum memory usage
  active: true                                  # the default is true

keys:
  - key: foo                                    # the key to be used in redis
    memory usage: 10mb                          # the maximum memory usage for the key
    length: 5                                   # the maximum length of the key
    span: 00:05:00                              # the time span which violation on the key limit will be considered ok
    exists: true                                # the job will fail if the key does not exist
    active: true                                # the default is true