defaults:                                       # default values for all folders. each folder can override these values
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:10                      # the interval between retry attemps
  maximum fails in row: 5                       # the maximum number of fails in row before the job is considered as failed

#hosts:                                         # the hosts to be used in the folder place holder {{host}}. usualy this section defined in specific environment job settings
#  - localhost
#  - 127.0.0.1
 
folders:
  - name: Customer X vault                      # the display name of the folder. required
    path: \\{{host}}\vaults\CustomerX           # the path of the folder 
    files pattern: "*.txt,*.dll"                # the pattern of the files to be monitored. this value is optional
    include subdirectories: true                # a flag to indicate if the subdirectories should be included in the monitoring or not. the defualt is false
    total size: 1gb                             # the maximum total size of the folder (in bytes, kb, mb, gb, tb, pb)
    file size: 10mb                             # the maximum size of single file (in bytes, kb, mb, gb, tb, pb)
    file count: 100                             # the maximum number of files in the folder
    created age: 1day                           # the maximum age of the file (in seconds, minutes, hours, days, weeks, months, years)
    modified age: 1day                          # the maximum age of the file (in seconds, minutes, hours, days, weeks, months, years)
