defaults:                                       # default values for all folders. each folder can override these values
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:10                      # the interval between retry attemps
  maximum fails in row: 5                       # the maximum number of fails in row before the job is considered as failed

#hosts:                                         # the hosts to be used in the folder place holder {{host}}. usualy this section defined in specific environment job settings
#  - localhost
#  - 127.0.0.1
 
folders:
  - name: Customer X vault                      # the display name of the folder
    path: \\{{host}}\vaults\CustomerX           # the path of the folder 
    monitor: size                               # the monitoring type of the folder. possible values are: size, file-size, count, created-age, modified-age
    monitor argument: 10mb                      # the monitoring argument value. the meaning of this value depends on the monitoring type
    files pattern: "*.txt,*.dll"                # the pattern of the files to be monitored. this value is optional
    include subdirectories: true                # a flag to indicate if the subdirectories should be included in the monitoring or not. the defualt is false
