$kind: http-request
url: http://localhost:2306/job/Infrastructure.BankOfIsraelCurrency/settings
method: GET
auth:
  type: noauth
scripts:
  - type: afterResponse
    code: "pm.test(\"Status code is 200\", function () {\r

      \    pm.response.to.have.status(200);\r

      });\r

      pm.test(\"Has value\", function () {\r

      \    var jsonData = pm.response.json();\r

      \    pm.expect(jsonData[0].value).to.not.empty;\r

      });"
    language: text/javascript
order: 8000
