server:                                        # the influx server parameters to be use. usualy this section defined in specific environment job settings
  url: http://localhost:8086
  token: xx
  organization: yy
