general:
  max degree of parallelism: 10                 # the maximum number of parallel threads to be used in the job. the default is 10. value between 2 and 100
  sequential processing: false                  # a flag to indicate if the tables should be processed sequentially or in parallel. the default is false

# connection strings:                           # the sql server connection strings to use. usualy this section defined in specific environment job settings
#   default: Data Source=.;Initial Catalog=master;Integrated Security=True

tables:
  - name: foo1                                  # the name of the query. required
    connection string name: default             # the connection string name to be used. required
    schema: Infrastructure                      # the schema of the table. required
    table name: CurrencyCode                    # the table name. required
    condition: DATEDIFF(DAY, CreateDate, GETDATE()) > 30 # the condition to be used in the query. the default is empty (TRUNCATE command will be used)
    batch size: 10000                           # the batch size to be used in the query. the default is 5,000. value between 1,000 and 50,000
    timeout: 00:10:00                           # the query execution timeout. the default is 10 minutes
    active: true                                # the default is true
