DROP INDEX IX_JobInstanceLog ON dbo.JobInstanceLog

GO

CREATE NONCLUSTERED INDEX IX_JobInstanceLog_JobId ON dbo.JobInstanceLog
	(
	JobId,
	StartDate
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_JobInstanceLog_Status ON dbo.JobInstanceLog
	(
	Status,
	StartDate
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

	GO

CREATE NONCLUSTERED INDEX IX_JobInstanceLog_JobGroup ON dbo.JobInstanceLog
	(
	JobGroup,
	StartDate
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


		GO

CREATE NONCLUSTERED INDEX IX_JobInstanceLog_JobType ON dbo.JobInstanceLog
	(
	JobType,
	StartDate
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_JobInstanceLog_InstanceId ON dbo.JobInstanceLog
	(
	InstanceId,
	StartDate
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]