DROP PROCEDURE dbo.PersistJobInstanceLog
DROP PROCEDURE dbo.UpdateJobInstanceLogAnomaly
DROP PROCEDURE dbo.SetJobInstanceLogStatus
DROP PROCEDURE dbo.DeleteUser
DROP PROCEDURE dbo.CountFailsInHourForJob
DROP PROCEDURE dbo.CountFailsInRowForJob
DROP PROCEDURE dbo.IncreaseMonitorCounter
DROP PROCEDURE dbo.ResetMonitorCounter
DROP PROCEDURE [Statistics].[StatusCounter]
DROP PROCEDURE [Statistics].[TraceCounter]