version: '3.4'

services:
  planar:
    image: atias007/planar:latest
    container_name: planar-service
    ports:
      - '2306:2306'
    environment:
      - TZ=Israel
      - PLANAR_DB_PROVIDER=SqlServer
      - PLANAR_DB_CONNECTION_STRING='Password=PlanarSqlPassword12345@;Persist Security Info=True;User ID=sa;Initial Catalog=Planar;Data Source=planar-db,1433;Encrypt=False'
    volumes:  
      - ./Planar/Data:/app/Data
    depends_on:
      - db
    networks:
      - planar_network
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: planar-db
    ports:
      - "6020:1433"
    environment:
      - TZ=Israel
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=PlanarSqlPassword12345@
    volumes:
      - dbvolume:/var/opt/mssql
    networks:
      - planar_network

volumes:
  dbvolume:

networks:
  planar_network:

# docker-compose -f docker-compose-sqlserver.yml -p planar up -d --remove-orphans