general:
  max degree of parallelism: 10                 # the maximum number of parallel threads to be used in the job. the default is 10. value between 2 and 100
  sequential processing: false                  # a flag to indicate if the endpoints should be processed sequentially or in parallel. the default is false
  stop running on fail: false                   # a flag to indicate if the job should stop running on fail in sequential processing. the default is false

defaults:                                       # default values for all endpoints. each endpoint can override these values
  success status codes: [200]                   # success status codes
  retry count: 3                                # the number of retry attemp in case of failure
  retry interval: 00:00:05                      # the interval between retry attemps
  timeout: 00:00:02                             # the timeout for each request
  allowed fail span: null                       # the time span which violation of the folder will be considered ok

#hosts:                                         # the hosts to be used in the endpoints with relative url. usualy this section defined in specific environment job settings
#  - group name: default
#    hosts:
#      - http://localhost
#      - http://127.0.0.1
 
endpoints:
  - name: Test internet access                 # the display name of the endpoint
    url: https://www.google.com                # the url of the endpoint
    bind to triggers:                          # this folder will be checked only when running with the following triggers. the default is null (run on any trigger execution)
      - every-1-hour                            
      - end-of-day
    allowed fail span: 00:01:00                # the time span which violation of the endpoint will be considered ok
    active: false                              # the default is true

  - name: GitHub
    url: https://github.com
    active: false

  - name: Consul
    host group name: default
    url: /
    port: 8500                                 # the port of the endpoint. the default is 80 for http and 443 for https

  - name: Seq
    url: http://localhost:5341

  - name: RabbitMQ
    host group name: default
    url: /api
    port: 15672
    active: true

  - name: Local IIS
    url: /
    host group name: default
    success status codes: [200]
    timeout: 00:00:05
    retry count: 3
    retry interval: 00:00:01
    active: true                               # the default is true