using System.Collections.Generic;
using System.Text.Json.Serialization;
using Planar.Client.Entities;

namespace Planar.Client.Exceptions
{
    internal class PlanarValidationErrors : IPlanarValidationErrors
    {
        //
        // Summary:
        //     A URI reference [RFC3986] that identifies the problem type. This specification
        //     encourages that, when dereferenced, it provide human-readable documentation for
        //     the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member
        //     is not present, its value is assumed to be "about:blank".
        [JsonPropertyName("type")]
#if NETSTANDARD2_0
        public string Type { get; set; }

#else
        public string Type { get; set; } = null!;

#endif

        //
        // Summary:
        //     A short, human-readable summary of the problem type.It SHOULD NOT change from
        //     occurrence to occurrence of the problem, except for purposes of localization(e.g.,
        //     using proactive content negotiation; see[RFC7231], Section 3.4).
        [JsonPropertyName("title")]
#if NETSTANDARD2_0
        public string Title { get; set; }

#else
        public string Title { get; set; } = null!;

#endif

        //
        // Summary:
        //     The HTTP status code([RFC7231], Section 6) generated by the origin server for
        //     this occurrence of the problem.
        [JsonPropertyName("status")]
        public int Status { get; set; }

        [JsonPropertyName("errorCode")]
        public int? ErrorCode { get; set; }

        //
        // Summary:
        //     A human-readable explanation specific to this occurrence of the problem.
        [JsonPropertyName("detail")]
#if NETSTANDARD2_0
        public string Detail { get; set; }

#else
        public string Detail { get; set; } = null!;

#endif

        //
        // Summary:
        //     A URI reference that identifies the specific occurrence of the problem.It may
        //     or may not yield further information if dereferenced.
        [JsonPropertyName("instance")]
#if NETSTANDARD2_0
        public string Instance { get; set; }

#else
        public string Instance { get; set; } = null!;

#endif

        [JsonPropertyName("errors")]
        public IEnumerable<PlanarError> Errors { get; set; } = new List<PlanarError>();
    }
}