$kind: http-request
url: http://localhost:2306/config/PostmanTestConfig
method: GET
auth:
  type: noauth
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
      });

      pm.test("Value was updated", function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData.key).to.equal("PostmanTestConfig");
          pm.expect(jsonData.value).to.equal("PostmanTestValueUpdated");
      });
    language: text/javascript
order: 7000
