$kind: http-request
url: http://localhost:2306/config/NonExistingPostmanKey
method: GET
auth:
  type: noauth
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 404", function () {
          pm.response.to.have.status(404);
      });
    language: text/javascript
order: 9000
