$kind: http-request
url: http://localhost:2306/config
method: POST
body:
  type: json
  content: |-
    {
        "key": "PostmanTestConfig",
        "value": "PostmanTestValue",
        "type": "string"
    }
auth:
  type: noauth
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 201", function () {
          pm.response.to.have.status(201);
      });
    language: text/javascript
order: 1000
