#hosts:                                         # the hosts to be used in folders with relative path. usualy this section defined in specific environment job settings
#  - localhost
#  - 127.0.0.1
 
folders:
  - name: Customer X vault                      # the display name of the folder. required
    path: \vaults\CustomerX                     # the path of the folder. relative or absolute path. required
    files pattern: "*.txt,*.dll"                # the pattern of the files to be monitored. this value is optional
    include subdirectories: true                # a flag to indicate if the subdirectories should be included in the monitoring or not. the defualt is false
    delete empty directories: true              # a flag to indicate if the empty directories should be deleted or not. the defualt is false
    file size: 10mb                             # the maximum size of single file (in bytes, kb, mb, gb, tb, pb)
    created age: 1day                           # the maximum age of the file (in seconds, minutes, hours, days, weeks, months, years)
    modified age: 1day                          # the maximum age of the file (in seconds, minutes, hours, days, weeks, months, years)
    max fails: 0                                # the maximum number of fails before fail the job. the default is 0 (no fails allow)
    active: true                                # check active or not. the default is true