defaults:                                       # default values for all streams. each stream can override these values
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:10                      # the interval between retry attemps
  maximum fails in row: 5                       # the maximum number of fails in row before the job is considered as failed

# rabbitmq:                                        # the rabbitmq server parameters to be use. usualy this section defined in specific environment job settings
#   api url: http://localhost:15672                # the rabbitmq api url
#   username: guest
#   password: guest

queues:
  - name: demo                                  # the name of the queue
    messages: 1000                              # the number of messages in the queue
    messages ready: null                        # the number of messages ready to be consumed  
    messages dlx: null                          # the number of messages in the dead letter exchange
    consumers: null                             # the number of consumers of the queue
    messages unacknowledged: null               # the number of unacknowledged messages
    messages rate: null                         # the rate of messages per second
    messages ready rate: null                   # the rate of messages ready to be consumed per second
    messages unacknowledged rate: null          # the rate of unacknowledged messages per second
    reductions: null                            # the number of reductions
    reductions rate: null                       # the rate of reductions per second
