general:
  max degree of parallelism: 10                 # the maximum number of parallel threads to be used in the job. the default is 10. value between 2 and 100
  sequential processing: false                  # a flag to indicate if the checks should be processed sequentially or in parallel. the default is false
  stop running on fail: false                   # a flag to indicate if the job should stop running on fail in sequential processing. the default is false

defaults:                                       # default values for all RabbitMq checks. health check and nodes can ovveride these values BUT not queues
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:05                      # the interval between retry attemps
  allowed fail span: 00:10:00                   # the time span which violation of health check will be considered ok

# server:                                       # the servers parameters to be use. usualy this section defined in specific environment job settings
#   hosts: 
#       - http://rabbitmq-server-1:15672                # the rabbitmq hosts
#       - http://rabbitmq-server-2:15672
#       - http://rabbitmq-server-3:15672 
#   username: guest
#   password: guest

health check:                                   # the health check parameters
  cluster alarm: true                           # if true, the job will fail if the cluster alarm is raised
  local alarm: true                             # if true, the job will fail if the local alarm is raised
  node mirror sync: true                        # if true, the job will fail if the node mirror sync is not ok (support only on RabbitMQ version below 4.0.0)
  node quorum critical: true                    # if true, the job will fail if the node quorum critical is not ok
  virtual hosts: true                           # if true, the job will fail if the virtual hosts are not ok
  bind to triggers:                             # this folder will be checked only when running with the following triggers. the default is null (run on any trigger execution)
    - every-1-hour                            
    - end-of-day
  allowed fail span: 00:10:00                   # the time span which violation of health check will be considered ok
  active: true                                  # the default is true

nodes:
  memory alarm: true                            # if true, the job will fail if the memory alarm is raised
  disk free alarm: true                         # if true, the job will fail if the disk free alarm is raised
  bind to triggers:                             # this folder will be checked only when running with the following triggers. the default is null (run on any trigger execution)
    - every-1-hour                            
    - end-of-day
  allowed fail span: 00:10:00                   # the time span which violation of the node will be considered ok
  active: true                                  # the default is true

queues:
  - name: demo                                  # the name of the queue
    memory: 2mb                                 # the maximum memory used by the queue (in bytes, kb, mb, gb, tb, pb)
    messages: 10                                # the maximum number of messages in the queue
    unacked: 10                                 # the minimum number of unacked messages in the queue
    consumers: null                             # the minimum number of consumers of the queue
    check state: true                           # if true, the job will fail if the queue state is not ok
    bind to triggers:                           # this folder will be checked only when running with the following triggers. the default is null (run on any trigger execution)
      - every-1-hour                            
      - end-of-day
    allowed fail span: 00:10:00                 # the time span which violation of the queue will be considered ok
    active: true                                # the default is true