defaults:                                       # default values for all streams. each stream can override these values
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:10                      # the interval between retry attemps
  maximum fails in row: 5                       # the maximum number of fails in row before the job is considered as failed

# rabbitmq:                                        # the rabbitmq server parameters to be use. usualy this section defined in specific environment job settings
#   api urls: [http://localhost:15672]             # the rabbitmq api urls
#   username: guest
#   password: guest

health check:                                   # the health check parameters
  cluster alarm: true                           # if true, the job will fail if the cluster alarm is raised
  local alarm: true                             # if true, the job will fail if the local alarm is raised
  node mirror sync: true                        # if true, the job will fail if the node mirror sync is not ok
  node quorum critical: true                    # if true, the job will fail if the node quorum critical is not ok

nodes:
  memory alarm: true                            # if true, the job will fail if the memory alarm is raised
  disk free alarm: true                         # if true, the job will fail if the disk free alarm is raised
  #name
  #running

queues:
  - name: demo                                  # the name of the queue
    messages: 1000                              # the number of messages in the queue
    consumers: null                             # the number of consumers of the queue
    memory: null                                # the memory used by the queue
    #status