server:                                      # the server parameters to be use. usualy this section defined in specific environment job settings
  hosts:
    - http://rabbitmq-server-1:15672		  # the rabbitmq host
    - http://rabbitmq-server-2:15672
    - http://rabbitmq-server-3:15672       
  username: some-username
  password: some-password