general:
  max degree of parallelism: 10                 # the maximum number of parallel threads to be used in the job. the default is 10. value between 2 and 100
  sequential processing: false                  # a flag to indicate if the services should be processed sequentially or in parallel. the default is false

defaults:                                       # default values for all services. each service can override these values
  retry count: 1                                # the number of retry attemp in case of failure
  retry interval: 00:00:01                      # the interval between retry attemps
  allowed fail span: null                       # the time span which violation of the folder will be considered ok

#hosts:                                         # the hosts to be used in folders with relative path. usualy this section defined in specific environment job settings
#  - group name: default
#    hosts:
#      - localhost
#      - 127.0.0.1
 
services:
  - name: MyServiceName                        # the name of the service
    host group name: default                   # when using relative folder path, 'host group name' must be supplied to a valid 'group name' in hosts section
    ignore disabled: true                      # ignore service which has start type: disabled. the default is true
    start service: true                        # start the service if it is stopped. the default is true
    start service timeout: 00:00:30            # the timeout for starting the service. the default is 30 seconds
    auto start mode: true                      # check for automatic start mode. the default is true
    bind to triggers:                          # this folder will be checked only when running with the following triggers. the default is null (run on any trigger execution)
      - every-1-hour                            
      - end-of-day
    allowed fail span: 00:05:00                # the time span which violation of the query will be considered ok
    active: true                               # the default is true
