// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.PauseAll~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.Pause(Planar.API.Common.Entities.JobOrTriggerKey)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.ResumeAll~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.Resume(Planar.API.Common.Entities.JobOrTriggerKey)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.RemoveData(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.Get(System.String)~System.Threading.Tasks.Task{Planar.API.Common.Entities.JobDetails}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.Remove(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.Invoke(Planar.API.Common.Entities.InvokeJobRequest)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.MonitorDomain.GetHooks~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.Get(System.String)~System.Threading.Tasks.Task{Planar.API.Common.Entities.TriggerRowDetails}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.GetByJob(System.String)~System.Threading.Tasks.Task{Planar.API.Common.Entities.TriggerRowDetails}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.Delete(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.Pause(Planar.API.Common.Entities.JobOrTriggerKey)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.Resume(Planar.API.Common.Entities.JobOrTriggerKey)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.GetRunning~System.Threading.Tasks.Task{System.Collections.Generic.List{Planar.API.Common.Entities.RunningJobDetails}}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.GetRunning(System.String)~System.Threading.Tasks.Task{Planar.API.Common.Entities.RunningJobDetails}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.ServiceDomain.GetCalendars~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.GetNextRunning(System.String)~System.Threading.Tasks.Task{System.Nullable{System.DateTime}}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.TriggerDomain.GetCronDescription(System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Planar BL Standart", Scope = "member", Target = "~M:Planar.Service.API.JobDomain.GetJobFileTemplate(System.String)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S3251:Implementations should be provided for \"partial\" methods", Justification = "DbContext", Scope = "member", Target = "~M:Planar.Service.Data.PlanarContext.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: SuppressMessage("Minor Code Smell", "S3251:Implementations should be provided for \"partial\" methods", Justification = "DbContext", Scope = "member", Target = "~M:Planar.Service.Data.PlanarContext.OnModelCreatingPartial(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "ISerializable", Scope = "type", Target = "~T:Planar.Service.Calendars.IsraelCalendar")]
[assembly: SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "ISerializable", Scope = "type", Target = "~T:Planar.Service.Calendars.GlobalCalendar")]
[assembly: SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "ISerializable", Scope = "type", Target = "~T:Planar.Service.Calendars.DefaultCalendar")]