SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Admin].[FactoryReset]
AS
DELETE FROM  [dbo].[QRTZ_BLOB_TRIGGERS]
DELETE FROM  [dbo].[QRTZ_CALENDARS]
DELETE FROM [dbo].[QRTZ_CRON_TRIGGERS]
DELETE FROM [dbo].[QRTZ_FIRED_TRIGGERS]
DELETE FROM [dbo].[QRTZ_LOCKS]
DELETE FROM [dbo].[QRTZ_PAUSED_TRIGGER_GRPS]
DELETE FROM [dbo].[QRTZ_SCHEDULER_STATE]
DELETE FROM [dbo].[QRTZ_SIMPLE_TRIGGERS]
DELETE FROM [dbo].[QRTZ_SIMPROP_TRIGGERS]
DELETE FROM [dbo].[QRTZ_TRIGGERS]
DELETE FROM [dbo].[QRTZ_JOB_DETAILS]

TRUNCATE TABLE [dbo].[ClusterNodes]
TRUNCATE TABLE [dbo].[GlobalConfig]

TRUNCATE TABLE [dbo].[JobInstanceLog]
TRUNCATE TABLE [dbo].[JobProperties]
TRUNCATE TABLE [dbo].[MonitorActions]
TRUNCATE TABLE [dbo].[Trace]
TRUNCATE TABLE [dbo].[UsersToGroups]


DELETE FROM [dbo].[Groups]
DELETE FROM [dbo].[Users]
DELETE FROM   [dbo].[Roles]
